// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// TODO: This is a placeholder file. To generate the real configuration:
// 1. Run: dart pub global run flutterfire_cli:flutterfire configure --project=YOUR_PROJECT_ID
// 2. Or run: flutterfire configure (if flutterfire is in your PATH)
// 3. Replace this entire file with the generated output
//
// Make sure you have:
// - Firebase project created at console.firebase.google.com
// - Flutter app registered in Firebase console
// - Email/Password auth enabled
// - Google Sign-In enabled
// - Firestore database created in test mode

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not configured - run flutterfire configure');
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  // TODO: Replace these placeholder values with your actual Firebase config
  // You can find these values in your Firebase Console → Project Settings → Your Apps

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZgc_C_yAxAIeq5HB9jfDLqC4agNXoloA',
    appId: '1:1014697157501:web:0daedc47ecc0fa5360e214',
    messagingSenderId: '1014697157501',
    projectId: 'allinone-app-3c707',
    authDomain: 'allinone-app-3c707.firebaseapp.com',
    storageBucket: 'allinone-app-3c707.firebasestorage.app',
    measurementId: 'G-L79WM8N0MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhfWcXbedrAItgKyazVpf_Qx5ZJBMd6VM',
    appId: '1:1014697157501:android:5cdc5f64731e7ba760e214',
    messagingSenderId: '1014697157501',
    projectId: 'allinone-app-3c707',
    storageBucket: 'allinone-app-3c707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOxmyokknNuh7KDk-CmW1vijpancU3PqY',
    appId: '1:1014697157501:ios:1fc962aeb83fda7260e214',
    messagingSenderId: '1014697157501',
    projectId: 'allinone-app-3c707',
    storageBucket: 'allinone-app-3c707.firebasestorage.app',
    iosBundleId: 'com.example.allinoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOxmyokknNuh7KDk-CmW1vijpancU3PqY',
    appId: '1:1014697157501:ios:1fc962aeb83fda7260e214',
    messagingSenderId: '1014697157501',
    projectId: 'allinone-app-3c707',
    storageBucket: 'allinone-app-3c707.firebasestorage.app',
    iosBundleId: 'com.example.allinoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZgc_C_yAxAIeq5HB9jfDLqC4agNXoloA',
    appId: '1:1014697157501:web:b71462dd4a1650d160e214',
    messagingSenderId: '1014697157501',
    projectId: 'allinone-app-3c707',
    authDomain: 'allinone-app-3c707.firebaseapp.com',
    storageBucket: 'allinone-app-3c707.firebasestorage.app',
    measurementId: 'G-P3VSGSRPRX',
  );

}